### PR TITLE
Return early if no API token, use edd_add_order_meta in 3.0

### LINKED ISSUE #14: EDD 3.0 - update how tax rate is stored with an order
The `store_taxjar_data_on_payment` method adds the tax data to the payment meta. This will need to be updated to populate the order object `tax` and add the proper order adjustments (if I recall, this will have to happen because there won't be a `tax_rate_id` to store with the order. 

Additionally, with the extension active, but no API key entered, the checkout in EDD 3.0 is broken with this error in edd-ajax.js: `Uncaught ReferenceError: tax_data is not defined`.

### PR DESCRIPTION
**Pull request by robincornett**
Fixes #14

### CODE REVIEW

File: edd-taxjar.php [hunk 1]
```diff
@@ -221,10 +221,18 @@ public function get_tax_rate( $rate = 0, $country = false, $state = false ) {
...
+		if ( empty( $this->api_token ) ) {
+			return;
+		}
+
 		$tax_data = EDD()->session->get( 'taxjar' );
 
 		if ( $tax_data ) {
-			$payment->add_meta( 'edd_taxjar_data', $tax_data );
+			if ( function_exists( 'edd_add_order_meta' ) ) {
+				edd_add_order_meta( $payment_id, 'tax_rate', $tax_data );
```
Comment (ashleyfae) [inline edd-taxjar.php:232]: Was changing the meta key intentional here?

**Review by ashleyfae — COMMENTED** [review]
Code looks good. Want to run a test first just to confirm.

**Review by ashleyfae — APPROVED** [review]
